# Generated by Django 4.2 on 2024-07-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('N', 'Normal'), ('P', 'Planta'), ('L', 'Lagartija'), ('A', 'Agua'), ('E', 'Eléctrico'), ('T', 'Tierra'), ('F', 'Fuego')], max_length=30),
        ),
    ]
